<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AngelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AngelRepository extends EntityRepository
{
}
